import pandas as pd
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

raw_path = Path('data/raw/Dataset .csv')
df = pd.read_csv(raw_path, encoding='utf-8-sig')
clean_df = df.drop_duplicates().copy().reset_index(drop=True)
output_dir = Path('data/cleaned')
output_dir.mkdir(parents=True, exist_ok=True)
clean_df.to_csv(output_dir / 'restaurant_cleaned.csv', index=False)

reports_dir = Path('reports')
reports_dir.mkdir(parents=True, exist_ok=True)
images_dir = Path('images')
images_dir.mkdir(parents=True, exist_ok=True)

cuisine_series = clean_df['Cuisines'].fillna('Unknown').str.split(', ')
cuisine_counts = cuisine_series.explode().value_counts()
top3 = cuisine_counts.head(3)
plt.figure(figsize=(8, 4))
top3.plot(kind='bar', color='#4C78A8')
plt.tight_layout()
plt.savefig(images_dir / 'task1_top_cuisines.png', dpi=300)
plt.close()
top3.to_csv(reports_dir / 'top_cuisines.csv')

city_count = clean_df['City'].value_counts().head(10)
city_rating = clean_df.groupby('City')['Aggregate rating'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(10, 4))
city_count.plot(kind='bar', color='#F58518')
plt.tight_layout()
plt.savefig(images_dir / 'task2_city_analysis.png', dpi=300)
plt.close()
plt.figure(figsize=(10, 4))
city_rating.plot(kind='bar', color='#54A24B')
plt.tight_layout()
plt.savefig(images_dir / 'task2_city_rating.png', dpi=300)
plt.close()
city_rating.to_csv(reports_dir / 'city_analysis.csv')

price_distribution = clean_df['Price range'].value_counts().sort_index()
plt.figure(figsize=(8, 4))
price_distribution.plot(kind='bar', color='#72B7B2')
plt.tight_layout()
plt.savefig(images_dir / 'task3_price_range.png', dpi=300)
plt.close()
price_distribution.to_csv(reports_dir / 'price_range_distribution.csv')

delivery_counts = clean_df['Has Online delivery'].value_counts()
rating_by_delivery = clean_df.groupby('Has Online delivery')['Aggregate rating'].mean()
plt.figure(figsize=(6, 6))
delivery_counts.plot(kind='pie', autopct='%1.1f%%', startangle=90, colors=['#4E79A7', '#F28E2B'])
plt.tight_layout()
plt.savefig(images_dir / 'task4_online_delivery.png', dpi=300)
plt.close()
rating_by_delivery.to_csv(reports_dir / 'online_delivery.csv')

print('Executed successfully')
print(clean_df.shape)
print(top3.to_dict())
print(city_count.head().to_dict())
print(price_distribution.to_dict())
print(delivery_counts.to_dict())
